// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_ScreenMain.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_speed_bg_png);    // assets/speed_bg.png
LV_IMG_DECLARE(ui_img_charge_bg_png);    // assets/charge_bg.png
LV_IMG_DECLARE(ui_img_power_bg_png);    // assets/power_bg.png
LV_IMG_DECLARE(ui_img_daytime_bg_png);    // assets/daytime_bg.png
LV_IMG_DECLARE(ui_img_bg_png);    // assets/bg.png
LV_IMG_DECLARE(ui_img_daytime_bluetooth_off_png);    // assets/daytime_bluetooth_off.png
LV_IMG_DECLARE(ui_img_daytime_wifi_off_png);    // assets/daytime_wifi_off.png
LV_IMG_DECLARE(ui_img_low_beam_png);    // assets/low_beam.png
LV_IMG_DECLARE(ui_img_high_beam_png);    // assets/high_beam.png
LV_IMG_DECLARE(ui_img_clearance_lamp_png);    // assets/clearance_lamp.png
LV_IMG_DECLARE(ui_img_day_time_png);    // assets/day_time.png
LV_IMG_DECLARE(ui_img_location_png);    // assets/location.png
LV_IMG_DECLARE(ui_img_ccs_png);    // assets/ccs.png
LV_IMG_DECLARE(ui_img_motor_fault_png);    // assets/motor_fault.png
LV_IMG_DECLARE(ui_img_soc_temp_high_png);    // assets/soc_temp_high.png
LV_IMG_DECLARE(ui_img_left_png);    // assets/left.png
LV_IMG_DECLARE(ui_img_right_png);    // assets/right.png
LV_IMG_DECLARE(ui_img_warning_png);    // assets/warning.png
LV_IMG_DECLARE(ui_img_choose1_png);    // assets/choose1.png
LV_IMG_DECLARE(ui_img_reverse_image_png);    // assets/reverse_image.png
LV_IMG_DECLARE(ui_img_projection_screen_png);    // assets/projection_screen.png
LV_IMG_DECLARE(ui_img_choose2_png);    // assets/choose2.png
LV_IMG_DECLARE(ui_img_bluetooth_png);    // assets/bluetooth.png
LV_IMG_DECLARE(ui_img_music_png);    // assets/music.png
LV_IMG_DECLARE(ui_img_charge_bar_png);    // assets/charge_bar.png
LV_IMG_DECLARE(ui_img_charge_bar_on_png);    // assets/charge_bar_on.png
LV_IMG_DECLARE(ui_img_ready_png);    // assets/ready.png
LV_IMG_DECLARE(ui_img_tires_bg_png);    // assets/tires_bg.png
LV_IMG_DECLARE(ui_img_endurance_mileage_png);    // assets/endurance_mileage.png
LV_IMG_DECLARE(ui_img_night_bg_png);    // assets/night_bg.png
LV_IMG_DECLARE(ui_img_night_bluetooth_off_png);    // assets/night_bluetooth_off.png
LV_IMG_DECLARE(ui_img_night_wifi_off_png);    // assets/night_wifi_off.png
LV_IMG_DECLARE(ui_img_bg_nitro_png);    // assets/bg_nitro.png
LV_IMG_DECLARE(ui_img_daytime_bluetooth_on_png);    // assets/daytime_bluetooth_on.png
LV_IMG_DECLARE(ui_img_daytime_wifi_on1_png);    // assets/daytime_wifi_on1.png
LV_IMG_DECLARE(ui_img_daytime_wifi_on2_png);    // assets/daytime_wifi_on2.png
LV_IMG_DECLARE(ui_img_daytime_wifi_on3_png);    // assets/daytime_wifi_on3.png
LV_IMG_DECLARE(ui_img_night_bluetooth_on_png);    // assets/night_bluetooth_on.png
LV_IMG_DECLARE(ui_img_night_wifi_on1_png);    // assets/night_wifi_on1.png
LV_IMG_DECLARE(ui_img_night_wifi_on2_png);    // assets/night_wifi_on2.png
LV_IMG_DECLARE(ui_img_night_wifi_on3_png);    // assets/night_wifi_on3.png

// FONTS
LV_FONT_DECLARE(ui_font_A4Font110);
LV_FONT_DECLARE(ui_font_MiSansBoldFont16);
LV_FONT_DECLARE(ui_font_MiSansBoldFont20);
LV_FONT_DECLARE(ui_font_MiSansBoldFont24);
LV_FONT_DECLARE(ui_font_MiSansHeavyFont20);
LV_FONT_DECLARE(ui_font_MiSansHeavyFont24);
LV_FONT_DECLARE(ui_font_MiSansHeavyFont26);
LV_FONT_DECLARE(ui_font_MiSansHeavyFont40);
LV_FONT_DECLARE(ui_font_MiSansRegularFont16);
LV_FONT_DECLARE(ui_font_MiSansRegularFont20);
LV_FONT_DECLARE(ui_font_YouSheBiaoTiFont26);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
