// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_normal[3] = {0x182F36, 0x182F36, 0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_normal[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_other[3] = {0xFFFFFF, 0xFFFFFF, 0x182F36};
const ui_theme_variable_t _ui_theme_alpha_other[3] = {255, 255, 255};
uint8_t ui_theme_idx = UI_THEME_DAYTIME;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

