// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScreenMain = NULL;
lv_obj_t * ui_Bar_speed_bg = NULL;
lv_obj_t * ui_Bar_charge_bg = NULL;
lv_obj_t * ui_Bar_power_bg = NULL;
lv_obj_t * ui_Image_bg1 = NULL;
lv_obj_t * ui_Image_bg2 = NULL;
lv_obj_t * ui_Container_top = NULL;
lv_obj_t * ui_Container_time = NULL;
lv_obj_t * ui_Label_time = NULL;
lv_obj_t * ui_Label_time_marker = NULL;
lv_obj_t * ui_Container_connect = NULL;
lv_obj_t * ui_Image_bluetooth_status = NULL;
lv_obj_t * ui_Image_wifi_status = NULL;
lv_obj_t * ui_Image_low_beam = NULL;
lv_obj_t * ui_Image_high_beam = NULL;
lv_obj_t * ui_Image_clearance_lamp = NULL;
lv_obj_t * ui_Image_day_time = NULL;
lv_obj_t * ui_Image_location = NULL;
lv_obj_t * ui_Image_ccs = NULL;
lv_obj_t * ui_Image_motor_fault = NULL;
lv_obj_t * ui_Image_soc_temp_high = NULL;
lv_obj_t * ui_Container_center = NULL;
lv_obj_t * ui_Image_left = NULL;
lv_obj_t * ui_Image_right = NULL;
lv_obj_t * ui_Label_speed_value = NULL;
lv_obj_t * ui_Label_gear_value = NULL;
lv_obj_t * ui_Label_charge_value = NULL;
lv_obj_t * ui_Panel_warning = NULL;
lv_obj_t * ui_Image_warning = NULL;
lv_obj_t * ui_Label_warning_info = NULL;
lv_obj_t * ui_Container_odo = NULL;
lv_obj_t * ui_Label_odo = NULL;
lv_obj_t * ui_Label_odo_value = NULL;
lv_obj_t * ui_Label_odo_km = NULL;
lv_obj_t * ui_Container_trip = NULL;
lv_obj_t * ui_Label_trip = NULL;
lv_obj_t * ui_Label_trip_value = NULL;
lv_obj_t * ui_Label_trip_km = NULL;
lv_obj_t * ui_Container_info_left = NULL;
lv_obj_t * ui_Container_reverse_image = NULL;
lv_obj_t * ui_Button_reverse_image = NULL;
lv_obj_t * ui_Image_reverse_image = NULL;
lv_obj_t * ui_Label_reverse_image = NULL;
lv_obj_t * ui_Container_projection_screen = NULL;
lv_obj_t * ui_Button_projection_screen = NULL;
lv_obj_t * ui_Image_projection_screen = NULL;
lv_obj_t * ui_Label_projection_screen = NULL;
lv_obj_t * ui_Container_bluetooth = NULL;
lv_obj_t * ui_Button_bluetooth = NULL;
lv_obj_t * ui_Image_bluetooth = NULL;
lv_obj_t * ui_Label_bluetooth = NULL;
lv_obj_t * ui_Container_music = NULL;
lv_obj_t * ui_Button_music = NULL;
lv_obj_t * ui_Image_music = NULL;
lv_obj_t * ui_Label_music = NULL;
lv_obj_t * ui_Container_info_right = NULL;
lv_obj_t * ui_Container_current_drain = NULL;
lv_obj_t * ui_Label_current_drain = NULL;
lv_obj_t * ui_Label_current_drain_value = NULL;
lv_obj_t * ui_Container_instantaneous_power = NULL;
lv_obj_t * ui_Label_instantaneous_power = NULL;
lv_obj_t * ui_Label_instantaneous_power_value = NULL;
lv_obj_t * ui_Container_surplus_power = NULL;
lv_obj_t * ui_Label_surplus_power = NULL;
lv_obj_t * ui_Label_surplus_power_value = NULL;
lv_obj_t * ui_Container_charging_power = NULL;
lv_obj_t * ui_Label_charging_power = NULL;
lv_obj_t * ui_Label_charging_power_value = NULL;
lv_obj_t * ui_Container_charge = NULL;
lv_obj_t * ui_Bar_charge = NULL;
lv_obj_t * ui_Label_charge_info = NULL;
lv_obj_t * ui_Container_bottom = NULL;
lv_obj_t * ui_Label_car_status = NULL;
lv_obj_t * ui_Label_model_status = NULL;
lv_obj_t * ui_Image_ready = NULL;
lv_obj_t * ui_Container_tires = NULL;
lv_obj_t * ui_Label_tire_pressure_front = NULL;
lv_obj_t * ui_Label_tire_temp_front = NULL;
lv_obj_t * ui_Label_tire_pressure_rear = NULL;
lv_obj_t * ui_Label_tire_temp_rear = NULL;
lv_obj_t * ui_Container_endurance_mileage = NULL;
lv_obj_t * ui_Image_endurance_mileage = NULL;
lv_obj_t * ui_Label_value_endurance_mileage = NULL;
lv_obj_t * ui_Bar_endurance_mileage = NULL;
lv_obj_t * ui_Button_test = NULL;
// event funtions
void ui_event_Button_test(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_switch_theme(UI_THEME_NIGHT);
        _ui_image_set_property(ui_Image_bg1, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_night_bg_png);
        _ui_image_set_property(ui_Image_bluetooth_status, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_night_bluetooth_off_png);
        _ui_image_set_property(ui_Image_wifi_status, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_night_wifi_off_png);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_switch_theme(UI_THEME_DAYTIME);
        _ui_image_set_property(ui_Image_bg1, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_daytime_bg_png);
        _ui_image_set_property(ui_Image_bluetooth_status, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_daytime_bluetooth_off_png);
        _ui_image_set_property(ui_Image_wifi_status, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_daytime_wifi_off_png);
    }
}

// build funtions

void ui_ScreenMain_screen_init(void)
{
    ui_ScreenMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenMain, lv_color_hex(0x557983), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar_speed_bg = lv_bar_create(ui_ScreenMain);
    lv_bar_set_value(ui_Bar_speed_bg, 60, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar_speed_bg, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar_speed_bg, 175);
    lv_obj_set_height(ui_Bar_speed_bg, 300);
    lv_obj_set_x(ui_Bar_speed_bg, 150);
    lv_obj_set_y(ui_Bar_speed_bg, 0);
    lv_obj_set_align(ui_Bar_speed_bg, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Bar_speed_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar_speed_bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar_speed_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar_speed_bg, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar_speed_bg, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar_speed_bg, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Bar_speed_bg, &ui_img_speed_bg_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Bar_charge_bg = lv_bar_create(ui_ScreenMain);
    lv_bar_set_value(ui_Bar_charge_bg, 60, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar_charge_bg, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar_charge_bg, 180);
    lv_obj_set_height(ui_Bar_charge_bg, 181);
    lv_obj_set_x(ui_Bar_charge_bg, -155);
    lv_obj_set_y(ui_Bar_charge_bg, 90);
    lv_obj_set_align(ui_Bar_charge_bg, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Bar_charge_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar_charge_bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar_charge_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar_charge_bg, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar_charge_bg, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar_charge_bg, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Bar_charge_bg, &ui_img_charge_bg_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Bar_power_bg = lv_bar_create(ui_ScreenMain);
    lv_bar_set_value(ui_Bar_power_bg, 40, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar_power_bg, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar_power_bg, 180);
    lv_obj_set_height(ui_Bar_power_bg, 181);
    lv_obj_set_x(ui_Bar_power_bg, -155);
    lv_obj_set_y(ui_Bar_power_bg, -90);
    lv_obj_set_align(ui_Bar_power_bg, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Bar_power_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar_power_bg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar_power_bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar_power_bg, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar_power_bg, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar_power_bg, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Bar_power_bg, &ui_img_power_bg_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Image_bg1 = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_Image_bg1, &ui_img_daytime_bg_png);
    lv_obj_set_width(ui_Image_bg1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_bg1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image_bg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_bg1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_bg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_bg2 = lv_img_create(ui_ScreenMain);
    lv_img_set_src(ui_Image_bg2, &ui_img_bg_png);
    lv_obj_set_width(ui_Image_bg2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_bg2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image_bg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_bg2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_bg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container_top = lv_obj_create(ui_ScreenMain);
    lv_obj_remove_style_all(ui_Container_top);
    lv_obj_set_height(ui_Container_top, 100);
    lv_obj_set_width(ui_Container_top, lv_pct(100));
    lv_obj_set_align(ui_Container_top, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container_top, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container_time = lv_obj_create(ui_Container_top);
    lv_obj_remove_style_all(ui_Container_time);
    lv_obj_set_width(ui_Container_time, 150);
    lv_obj_set_height(ui_Container_time, 46);
    lv_obj_set_x(ui_Container_time, -320);
    lv_obj_set_y(ui_Container_time, 8);
    lv_obj_set_align(ui_Container_time, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container_time, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_time = lv_label_create(ui_Container_time);
    lv_obj_set_width(ui_Label_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_time, -28);
    lv_obj_set_y(ui_Label_time, 0);
    lv_obj_set_align(ui_Label_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_time, "08:20");
    ui_object_set_themeable_style_property(ui_Label_time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_normal);
    ui_object_set_themeable_style_property(ui_Label_time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_normal);
    lv_obj_set_style_text_font(ui_Label_time, &ui_font_MiSansHeavyFont26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_time_marker = lv_label_create(ui_Container_time);
    lv_obj_set_width(ui_Label_time_marker, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_time_marker, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_time_marker, 44);
    lv_obj_set_y(ui_Label_time_marker, 4);
    lv_obj_set_align(ui_Label_time_marker, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_time_marker, "AM");
    ui_object_set_themeable_style_property(ui_Label_time_marker, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_normal);
    ui_object_set_themeable_style_property(ui_Label_time_marker, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_normal);
    lv_obj_set_style_text_font(ui_Label_time_marker, &ui_font_MiSansHeavyFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_connect = lv_obj_create(ui_Container_top);
    lv_obj_remove_style_all(ui_Container_connect);
    lv_obj_set_width(ui_Container_connect, 86);
    lv_obj_set_height(ui_Container_connect, 44);
    lv_obj_set_x(ui_Container_connect, 346);
    lv_obj_set_y(ui_Container_connect, 8);
    lv_obj_set_align(ui_Container_connect, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container_connect, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_bluetooth_status = lv_img_create(ui_Container_connect);
    lv_img_set_src(ui_Image_bluetooth_status, &ui_img_daytime_bluetooth_off_png);
    lv_obj_set_width(ui_Image_bluetooth_status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_bluetooth_status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_bluetooth_status, -17);
    lv_obj_set_y(ui_Image_bluetooth_status, 0);
    lv_obj_set_align(ui_Image_bluetooth_status, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_bluetooth_status, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_bluetooth_status, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_wifi_status = lv_img_create(ui_Container_connect);
    lv_img_set_src(ui_Image_wifi_status, &ui_img_daytime_wifi_off_png);
    lv_obj_set_width(ui_Image_wifi_status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_wifi_status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_wifi_status, 17);
    lv_obj_set_y(ui_Image_wifi_status, 0);
    lv_obj_set_align(ui_Image_wifi_status, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_wifi_status, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_wifi_status, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_low_beam = lv_img_create(ui_Container_top);
    lv_img_set_src(ui_Image_low_beam, &ui_img_low_beam_png);
    lv_obj_set_width(ui_Image_low_beam, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_low_beam, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_low_beam, -200);
    lv_obj_set_y(ui_Image_low_beam, 8);
    lv_obj_set_align(ui_Image_low_beam, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image_low_beam, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_low_beam, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_high_beam = lv_img_create(ui_Container_top);
    lv_img_set_src(ui_Image_high_beam, &ui_img_high_beam_png);
    lv_obj_set_width(ui_Image_high_beam, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_high_beam, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_high_beam, -120);
    lv_obj_set_y(ui_Image_high_beam, 8);
    lv_obj_set_align(ui_Image_high_beam, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image_high_beam, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_high_beam, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_clearance_lamp = lv_img_create(ui_Container_top);
    lv_img_set_src(ui_Image_clearance_lamp, &ui_img_clearance_lamp_png);
    lv_obj_set_width(ui_Image_clearance_lamp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_clearance_lamp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_clearance_lamp, -40);
    lv_obj_set_y(ui_Image_clearance_lamp, 8);
    lv_obj_set_align(ui_Image_clearance_lamp, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image_clearance_lamp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_clearance_lamp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_day_time = lv_img_create(ui_Container_top);
    lv_img_set_src(ui_Image_day_time, &ui_img_day_time_png);
    lv_obj_set_width(ui_Image_day_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_day_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_day_time, 40);
    lv_obj_set_y(ui_Image_day_time, 8);
    lv_obj_set_align(ui_Image_day_time, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image_day_time, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_day_time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_location = lv_img_create(ui_Container_top);
    lv_img_set_src(ui_Image_location, &ui_img_location_png);
    lv_obj_set_width(ui_Image_location, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_location, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_location, 120);
    lv_obj_set_y(ui_Image_location, 8);
    lv_obj_set_align(ui_Image_location, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image_location, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_location, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_ccs = lv_img_create(ui_Container_top);
    lv_img_set_src(ui_Image_ccs, &ui_img_ccs_png);
    lv_obj_set_width(ui_Image_ccs, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_ccs, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_ccs, 200);
    lv_obj_set_y(ui_Image_ccs, 8);
    lv_obj_set_align(ui_Image_ccs, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image_ccs, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_ccs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_motor_fault = lv_img_create(ui_Container_top);
    lv_img_set_src(ui_Image_motor_fault, &ui_img_motor_fault_png);
    lv_obj_set_width(ui_Image_motor_fault, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_motor_fault, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_motor_fault, -110);
    lv_obj_set_y(ui_Image_motor_fault, 50);
    lv_obj_set_align(ui_Image_motor_fault, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image_motor_fault, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_motor_fault, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_soc_temp_high = lv_img_create(ui_Container_top);
    lv_img_set_src(ui_Image_soc_temp_high, &ui_img_soc_temp_high_png);
    lv_obj_set_width(ui_Image_soc_temp_high, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_soc_temp_high, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_soc_temp_high, 110);
    lv_obj_set_y(ui_Image_soc_temp_high, 50);
    lv_obj_set_align(ui_Image_soc_temp_high, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image_soc_temp_high, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_soc_temp_high, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container_center = lv_obj_create(ui_ScreenMain);
    lv_obj_remove_style_all(ui_Container_center);
    lv_obj_set_height(ui_Container_center, 370);
    lv_obj_set_width(ui_Container_center, lv_pct(100));
    lv_obj_set_align(ui_Container_center, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container_center, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_left = lv_img_create(ui_Container_center);
    lv_img_set_src(ui_Image_left, &ui_img_left_png);
    lv_obj_set_width(ui_Image_left, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_left, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_left, -360);
    lv_obj_set_y(ui_Image_left, -110);
    lv_obj_set_align(ui_Image_left, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_left, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_left, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_right = lv_img_create(ui_Container_center);
    lv_img_set_src(ui_Image_right, &ui_img_right_png);
    lv_obj_set_width(ui_Image_right, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_right, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_right, 360);
    lv_obj_set_y(ui_Image_right, -110);
    lv_obj_set_align(ui_Image_right, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_right, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_right, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_speed_value = lv_label_create(ui_Container_center);
    lv_obj_set_width(ui_Label_speed_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_speed_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_speed_value, 0);
    lv_obj_set_y(ui_Label_speed_value, 2);
    lv_obj_set_align(ui_Label_speed_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_speed_value, "69");
    lv_obj_set_style_text_color(ui_Label_speed_value, lv_color_hex(0x355ADF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_speed_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_speed_value, &ui_font_A4Font110, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_gear_value = lv_label_create(ui_Container_center);
    lv_obj_set_width(ui_Label_gear_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_gear_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_gear_value, 0);
    lv_obj_set_y(ui_Label_gear_value, 125);
    lv_obj_set_align(ui_Label_gear_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_gear_value, "D");
    lv_obj_set_style_text_color(ui_Label_gear_value, lv_color_hex(0x355ADF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_gear_value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_gear_value, &ui_font_MiSansHeavyFont40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_charge_value = lv_label_create(ui_Container_center);
    lv_obj_set_width(ui_Label_charge_value, 70);
    lv_obj_set_height(ui_Label_charge_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_charge_value, -190);
    lv_obj_set_y(ui_Label_charge_value, 140);
    lv_obj_set_align(ui_Label_charge_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_charge_value, "70%");
    ui_object_set_themeable_style_property(ui_Label_charge_value, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_normal);
    ui_object_set_themeable_style_property(ui_Label_charge_value, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_normal);
    lv_obj_set_style_text_align(ui_Label_charge_value, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_charge_value, &ui_font_MiSansHeavyFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_warning = lv_obj_create(ui_Container_center);
    lv_obj_set_width(ui_Panel_warning, 310);
    lv_obj_set_height(ui_Panel_warning, 50);
    lv_obj_set_x(ui_Panel_warning, 0);
    lv_obj_set_y(ui_Panel_warning, -110);
    lv_obj_set_align(ui_Panel_warning, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel_warning, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel_warning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel_warning, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel_warning, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_warning, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_warning, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_warning, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_warning, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_warning = lv_img_create(ui_Panel_warning);
    lv_img_set_src(ui_Image_warning, &ui_img_warning_png);
    lv_obj_set_width(ui_Image_warning, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_warning, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_warning, -130);
    lv_obj_set_y(ui_Image_warning, 0);
    lv_obj_set_align(ui_Image_warning, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_warning, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_warning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_warning_info = lv_label_create(ui_Panel_warning);
    lv_obj_set_width(ui_Label_warning_info, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_warning_info, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_warning_info, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_warning_info, "胎压过高!");
    lv_obj_set_style_text_color(ui_Label_warning_info, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_warning_info, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_warning_info, &ui_font_MiSansHeavyFont20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_odo = lv_obj_create(ui_Container_center);
    lv_obj_remove_style_all(ui_Container_odo);
    lv_obj_set_width(ui_Container_odo, 170);
    lv_obj_set_height(ui_Container_odo, 30);
    lv_obj_set_x(ui_Container_odo, -300);
    lv_obj_set_y(ui_Container_odo, -160);
    lv_obj_set_align(ui_Container_odo, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container_odo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_odo = lv_label_create(ui_Container_odo);
    lv_obj_set_width(ui_Label_odo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_odo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_odo, -60);
    lv_obj_set_y(ui_Label_odo, 0);
    lv_obj_set_align(ui_Label_odo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_odo, "ODO");
    ui_object_set_themeable_style_property(ui_Label_odo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_normal);
    ui_object_set_themeable_style_property(ui_Label_odo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_normal);
    lv_obj_set_style_text_font(ui_Label_odo, &ui_font_MiSansBoldFont20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_odo_value = lv_label_create(ui_Container_odo);
    lv_obj_set_width(ui_Label_odo_value, 70);
    lv_obj_set_height(ui_Label_odo_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_odo_value, 5);
    lv_obj_set_y(ui_Label_odo_value, 0);
    lv_obj_set_align(ui_Label_odo_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_odo_value, "456");
    ui_object_set_themeable_style_property(ui_Label_odo_value, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_normal);
    ui_object_set_themeable_style_property(ui_Label_odo_value, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_normal);
    lv_obj_set_style_text_align(ui_Label_odo_value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_odo_value, &ui_font_MiSansHeavyFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_odo_km = lv_label_create(ui_Container_odo);
    lv_obj_set_width(ui_Label_odo_km, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_odo_km, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_odo_km, 65);
    lv_obj_set_y(ui_Label_odo_km, 0);
    lv_obj_set_align(ui_Label_odo_km, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_odo_km, "km");
    ui_object_set_themeable_style_property(ui_Label_odo_km, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_normal);
    ui_object_set_themeable_style_property(ui_Label_odo_km, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_normal);
    lv_obj_set_style_text_font(ui_Label_odo_km, &ui_font_MiSansBoldFont20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_trip = lv_obj_create(ui_Container_center);
    lv_obj_remove_style_all(ui_Container_trip);
    lv_obj_set_width(ui_Container_trip, 170);
    lv_obj_set_height(ui_Container_trip, 30);
    lv_obj_set_x(ui_Container_trip, 300);
    lv_obj_set_y(ui_Container_trip, -160);
    lv_obj_set_align(ui_Container_trip, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container_trip, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_trip = lv_label_create(ui_Container_trip);
    lv_obj_set_width(ui_Label_trip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_trip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_trip, -60);
    lv_obj_set_y(ui_Label_trip, 0);
    lv_obj_set_align(ui_Label_trip, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_trip, "TRIP");
    ui_object_set_themeable_style_property(ui_Label_trip, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_normal);
    ui_object_set_themeable_style_property(ui_Label_trip, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_normal);
    lv_obj_set_style_text_font(ui_Label_trip, &ui_font_MiSansBoldFont20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_trip_value = lv_label_create(ui_Container_trip);
    lv_obj_set_width(ui_Label_trip_value, 70);
    lv_obj_set_height(ui_Label_trip_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_trip_value, 5);
    lv_obj_set_y(ui_Label_trip_value, 0);
    lv_obj_set_align(ui_Label_trip_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_trip_value, "0.7");
    ui_object_set_themeable_style_property(ui_Label_trip_value, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_normal);
    ui_object_set_themeable_style_property(ui_Label_trip_value, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_normal);
    lv_obj_set_style_text_align(ui_Label_trip_value, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_trip_value, &ui_font_MiSansHeavyFont24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_trip_km = lv_label_create(ui_Container_trip);
    lv_obj_set_width(ui_Label_trip_km, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_trip_km, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_trip_km, 65);
    lv_obj_set_y(ui_Label_trip_km, 0);
    lv_obj_set_align(ui_Label_trip_km, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_trip_km, "km");
    ui_object_set_themeable_style_property(ui_Label_trip_km, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_normal);
    ui_object_set_themeable_style_property(ui_Label_trip_km, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_normal);
    lv_obj_set_style_text_font(ui_Label_trip_km, &ui_font_MiSansBoldFont20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_info_left = lv_obj_create(ui_Container_center);
    lv_obj_remove_style_all(ui_Container_info_left);
    lv_obj_set_width(ui_Container_info_left, 200);
    lv_obj_set_height(ui_Container_info_left, 210);
    lv_obj_set_x(ui_Container_info_left, -285);
    lv_obj_set_y(ui_Container_info_left, 0);
    lv_obj_set_align(ui_Container_info_left, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container_info_left, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container_info_left, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container_info_left, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container_reverse_image = lv_obj_create(ui_Container_info_left);
    lv_obj_remove_style_all(ui_Container_reverse_image);
    lv_obj_set_width(ui_Container_reverse_image, lv_pct(100));
    lv_obj_set_height(ui_Container_reverse_image, lv_pct(25));
    lv_obj_set_x(ui_Container_reverse_image, 0);
    lv_obj_set_y(ui_Container_reverse_image, -79);
    lv_obj_set_align(ui_Container_reverse_image, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container_reverse_image, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button_reverse_image = lv_btn_create(ui_Container_reverse_image);
    lv_obj_set_width(ui_Button_reverse_image, 106);
    lv_obj_set_height(ui_Button_reverse_image, 33);
    lv_obj_set_align(ui_Button_reverse_image, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button_reverse_image, LV_STATE_USER_1);       /// States
    lv_obj_add_flag(ui_Button_reverse_image, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_reverse_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button_reverse_image, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button_reverse_image, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_reverse_image, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button_reverse_image, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button_reverse_image, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Button_reverse_image, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Button_reverse_image, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_reverse_image, &ui_img_choose1_png, LV_PART_MAIN | LV_STATE_USER_1);

    ui_Image_reverse_image = lv_img_create(ui_Button_reverse_image);
    lv_img_set_src(ui_Image_reverse_image, &ui_img_reverse_image_png);
    lv_obj_set_width(ui_Image_reverse_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_reverse_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_reverse_image, -15);
    lv_obj_set_y(ui_Image_reverse_image, 0);
    lv_obj_set_align(ui_Image_reverse_image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_reverse_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_reverse_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Image_reverse_image, lv_color_hex(0x182F36), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image_reverse_image, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_reverse_image = lv_label_create(ui_Container_reverse_image);
    lv_obj_set_width(ui_Label_reverse_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_reverse_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_reverse_image, 50);
    lv_obj_set_y(ui_Label_reverse_image, 0);
    lv_obj_set_align(ui_Label_reverse_image, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_reverse_image, "倒车影像");
    ui_object_set_themeable_style_property(ui_Label_reverse_image, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_normal);
    ui_object_set_themeable_style_property(ui_Label_reverse_image, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_normal);
    lv_obj_set_style_text_font(ui_Label_reverse_image, &ui_font_MiSansRegularFont20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_projection_screen = lv_obj_create(ui_Container_info_left);
    lv_obj_remove_style_all(ui_Container_projection_screen);
    lv_obj_set_width(ui_Container_projection_screen, lv_pct(100));
    lv_obj_set_height(ui_Container_projection_screen, lv_pct(25));
    lv_obj_set_x(ui_Container_projection_screen, 0);
    lv_obj_set_y(ui_Container_projection_screen, -28);
    lv_obj_set_align(ui_Container_projection_screen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container_projection_screen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button_projection_screen = lv_btn_create(ui_Container_projection_screen);
    lv_obj_set_width(ui_Button_projection_screen, 106);
    lv_obj_set_height(ui_Button_projection_screen, 33);
    lv_obj_set_x(ui_Button_projection_screen, -40);
    lv_obj_set_y(ui_Button_projection_screen, 0);
    lv_obj_set_align(ui_Button_projection_screen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button_projection_screen, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_projection_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button_projection_screen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button_projection_screen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_projection_screen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button_projection_screen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button_projection_screen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Button_projection_screen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Button_projection_screen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_projection_screen, &ui_img_choose1_png, LV_PART_MAIN | LV_STATE_USER_1);

    ui_Image_projection_screen = lv_img_create(ui_Button_projection_screen);
    lv_img_set_src(ui_Image_projection_screen, &ui_img_projection_screen_png);
    lv_obj_set_width(ui_Image_projection_screen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_projection_screen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_projection_screen, -15);
    lv_obj_set_y(ui_Image_projection_screen, 0);
    lv_obj_set_align(ui_Image_projection_screen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_projection_screen, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_projection_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Image_projection_screen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image_projection_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_projection_screen = lv_label_create(ui_Container_projection_screen);
    lv_obj_set_width(ui_Label_projection_screen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_projection_screen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_projection_screen, 10);
    lv_obj_set_y(ui_Label_projection_screen, 0);
    lv_obj_set_align(ui_Label_projection_screen, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_projection_screen, "投屏");
    lv_obj_add_flag(ui_Label_projection_screen, LV_OBJ_FLAG_HIDDEN);     /// Flags
    ui_object_set_themeable_style_property(ui_Label_projection_screen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_normal);
    ui_object_set_themeable_style_property(ui_Label_projection_screen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_normal);
    lv_obj_set_style_text_font(ui_Label_projection_screen, &ui_font_MiSansRegularFont20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_bluetooth = lv_obj_create(ui_Container_info_left);
    lv_obj_remove_style_all(ui_Container_bluetooth);
    lv_obj_set_width(ui_Container_bluetooth, lv_pct(100));
    lv_obj_set_height(ui_Container_bluetooth, lv_pct(25));
    lv_obj_set_x(ui_Container_bluetooth, 0);
    lv_obj_set_y(ui_Container_bluetooth, 23);
    lv_obj_set_align(ui_Container_bluetooth, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container_bluetooth, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button_bluetooth = lv_btn_create(ui_Container_bluetooth);
    lv_obj_set_width(ui_Button_bluetooth, 106);
    lv_obj_set_height(ui_Button_bluetooth, 33);
    lv_obj_set_x(ui_Button_bluetooth, -40);
    lv_obj_set_y(ui_Button_bluetooth, 0);
    lv_obj_set_align(ui_Button_bluetooth, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button_bluetooth, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_bluetooth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button_bluetooth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button_bluetooth, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_bluetooth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button_bluetooth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button_bluetooth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Button_bluetooth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Button_bluetooth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_bluetooth, &ui_img_choose2_png, LV_PART_MAIN | LV_STATE_USER_1);

    ui_Image_bluetooth = lv_img_create(ui_Button_bluetooth);
    lv_img_set_src(ui_Image_bluetooth, &ui_img_bluetooth_png);
    lv_obj_set_width(ui_Image_bluetooth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_bluetooth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_bluetooth, -15);
    lv_obj_set_y(ui_Image_bluetooth, 0);
    lv_obj_set_align(ui_Image_bluetooth, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_bluetooth, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_bluetooth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Image_bluetooth, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image_bluetooth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_bluetooth = lv_label_create(ui_Container_bluetooth);
    lv_obj_set_width(ui_Label_bluetooth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_bluetooth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_bluetooth, 10);
    lv_obj_set_y(ui_Label_bluetooth, 0);
    lv_obj_set_align(ui_Label_bluetooth, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_bluetooth, "蓝牙");
    lv_obj_add_flag(ui_Label_bluetooth, LV_OBJ_FLAG_HIDDEN);     /// Flags
    ui_object_set_themeable_style_property(ui_Label_bluetooth, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_normal);
    ui_object_set_themeable_style_property(ui_Label_bluetooth, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_normal);
    lv_obj_set_style_text_font(ui_Label_bluetooth, &ui_font_MiSansRegularFont20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_music = lv_obj_create(ui_Container_info_left);
    lv_obj_remove_style_all(ui_Container_music);
    lv_obj_set_width(ui_Container_music, lv_pct(100));
    lv_obj_set_height(ui_Container_music, lv_pct(25));
    lv_obj_set_x(ui_Container_music, 0);
    lv_obj_set_y(ui_Container_music, 74);
    lv_obj_set_align(ui_Container_music, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container_music, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button_music = lv_btn_create(ui_Container_music);
    lv_obj_set_width(ui_Button_music, 106);
    lv_obj_set_height(ui_Button_music, 33);
    lv_obj_set_align(ui_Button_music, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button_music, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_music, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button_music, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button_music, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button_music, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Button_music, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Button_music, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Button_music, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Button_music, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button_music, &ui_img_choose2_png, LV_PART_MAIN | LV_STATE_USER_1);

    ui_Image_music = lv_img_create(ui_Button_music);
    lv_img_set_src(ui_Image_music, &ui_img_music_png);
    lv_obj_set_width(ui_Image_music, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_music, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_music, -15);
    lv_obj_set_y(ui_Image_music, 0);
    lv_obj_set_align(ui_Image_music, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_music, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_music, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Image_music, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image_music, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_music = lv_label_create(ui_Container_music);
    lv_obj_set_width(ui_Label_music, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_music, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_music, 50);
    lv_obj_set_y(ui_Label_music, 0);
    lv_obj_set_align(ui_Label_music, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_music, "音乐");
    lv_obj_add_flag(ui_Label_music, LV_OBJ_FLAG_HIDDEN);     /// Flags
    ui_object_set_themeable_style_property(ui_Label_music, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_normal);
    ui_object_set_themeable_style_property(ui_Label_music, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_normal);
    lv_obj_set_style_text_font(ui_Label_music, &ui_font_MiSansRegularFont20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_info_right = lv_obj_create(ui_Container_center);
    lv_obj_remove_style_all(ui_Container_info_right);
    lv_obj_set_width(ui_Container_info_right, 160);
    lv_obj_set_height(ui_Container_info_right, 210);
    lv_obj_set_x(ui_Container_info_right, 285);
    lv_obj_set_y(ui_Container_info_right, 0);
    lv_obj_set_align(ui_Container_info_right, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container_info_right, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container_info_right, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container_info_right, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container_current_drain = lv_obj_create(ui_Container_info_right);
    lv_obj_remove_style_all(ui_Container_current_drain);
    lv_obj_set_width(ui_Container_current_drain, lv_pct(100));
    lv_obj_set_height(ui_Container_current_drain, lv_pct(25));
    lv_obj_set_x(ui_Container_current_drain, 0);
    lv_obj_set_y(ui_Container_current_drain, -77);
    lv_obj_set_align(ui_Container_current_drain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container_current_drain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_current_drain = lv_label_create(ui_Container_current_drain);
    lv_obj_set_width(ui_Label_current_drain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_current_drain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_current_drain, -20);
    lv_obj_set_y(ui_Label_current_drain, -10);
    lv_obj_set_align(ui_Label_current_drain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_current_drain, "平均电耗");
    ui_object_set_themeable_style_property(ui_Label_current_drain, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_normal);
    ui_object_set_themeable_style_property(ui_Label_current_drain, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_normal);
    lv_obj_set_style_text_font(ui_Label_current_drain, &ui_font_MiSansRegularFont16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_current_drain_value = lv_label_create(ui_Container_current_drain);
    lv_obj_set_width(ui_Label_current_drain_value, 130);
    lv_obj_set_height(ui_Label_current_drain_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_current_drain_value, -15);
    lv_obj_set_y(ui_Label_current_drain_value, 10);
    lv_obj_set_align(ui_Label_current_drain_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_current_drain_value, "0.0 kwh/100km");
    ui_object_set_themeable_style_property(ui_Label_current_drain_value, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_normal);
    ui_object_set_themeable_style_property(ui_Label_current_drain_value, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_normal);
    lv_obj_set_style_text_align(ui_Label_current_drain_value, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_current_drain_value, &ui_font_MiSansRegularFont16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_instantaneous_power = lv_obj_create(ui_Container_info_right);
    lv_obj_remove_style_all(ui_Container_instantaneous_power);
    lv_obj_set_width(ui_Container_instantaneous_power, lv_pct(100));
    lv_obj_set_height(ui_Container_instantaneous_power, lv_pct(25));
    lv_obj_set_x(ui_Container_instantaneous_power, 0);
    lv_obj_set_y(ui_Container_instantaneous_power, -26);
    lv_obj_set_align(ui_Container_instantaneous_power, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container_instantaneous_power, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_instantaneous_power = lv_label_create(ui_Container_instantaneous_power);
    lv_obj_set_width(ui_Label_instantaneous_power, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_instantaneous_power, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_instantaneous_power, 15);
    lv_obj_set_y(ui_Label_instantaneous_power, -10);
    lv_obj_set_align(ui_Label_instantaneous_power, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_instantaneous_power, "瞬时功率");
    ui_object_set_themeable_style_property(ui_Label_instantaneous_power, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_normal);
    ui_object_set_themeable_style_property(ui_Label_instantaneous_power, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_normal);
    lv_obj_set_style_text_font(ui_Label_instantaneous_power, &ui_font_MiSansRegularFont16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_instantaneous_power_value = lv_label_create(ui_Container_instantaneous_power);
    lv_obj_set_width(ui_Label_instantaneous_power_value, 80);
    lv_obj_set_height(ui_Label_instantaneous_power_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_instantaneous_power_value, 0);
    lv_obj_set_y(ui_Label_instantaneous_power_value, 10);
    lv_obj_set_align(ui_Label_instantaneous_power_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_instantaneous_power_value, "000 kw");
    ui_object_set_themeable_style_property(ui_Label_instantaneous_power_value, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_normal);
    ui_object_set_themeable_style_property(ui_Label_instantaneous_power_value, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_normal);
    lv_obj_set_style_text_align(ui_Label_instantaneous_power_value, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_instantaneous_power_value, &ui_font_MiSansRegularFont16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_surplus_power = lv_obj_create(ui_Container_info_right);
    lv_obj_remove_style_all(ui_Container_surplus_power);
    lv_obj_set_width(ui_Container_surplus_power, lv_pct(100));
    lv_obj_set_height(ui_Container_surplus_power, lv_pct(25));
    lv_obj_set_x(ui_Container_surplus_power, 0);
    lv_obj_set_y(ui_Container_surplus_power, 25);
    lv_obj_set_align(ui_Container_surplus_power, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container_surplus_power, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_surplus_power = lv_label_create(ui_Container_surplus_power);
    lv_obj_set_width(ui_Label_surplus_power, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_surplus_power, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_surplus_power, 15);
    lv_obj_set_y(ui_Label_surplus_power, -10);
    lv_obj_set_align(ui_Label_surplus_power, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_surplus_power, "剩余功率");
    ui_object_set_themeable_style_property(ui_Label_surplus_power, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_normal);
    ui_object_set_themeable_style_property(ui_Label_surplus_power, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_normal);
    lv_obj_set_style_text_font(ui_Label_surplus_power, &ui_font_MiSansRegularFont16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_surplus_power_value = lv_label_create(ui_Container_surplus_power);
    lv_obj_set_width(ui_Label_surplus_power_value, 80);
    lv_obj_set_height(ui_Label_surplus_power_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_surplus_power_value, 0);
    lv_obj_set_y(ui_Label_surplus_power_value, 10);
    lv_obj_set_align(ui_Label_surplus_power_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_surplus_power_value, "000 kw");
    ui_object_set_themeable_style_property(ui_Label_surplus_power_value, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_normal);
    ui_object_set_themeable_style_property(ui_Label_surplus_power_value, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_normal);
    lv_obj_set_style_text_align(ui_Label_surplus_power_value, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_surplus_power_value, &ui_font_MiSansRegularFont16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_charging_power = lv_obj_create(ui_Container_info_right);
    lv_obj_remove_style_all(ui_Container_charging_power);
    lv_obj_set_width(ui_Container_charging_power, lv_pct(100));
    lv_obj_set_height(ui_Container_charging_power, lv_pct(25));
    lv_obj_set_x(ui_Container_charging_power, 0);
    lv_obj_set_y(ui_Container_charging_power, 76);
    lv_obj_set_align(ui_Container_charging_power, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container_charging_power, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_charging_power = lv_label_create(ui_Container_charging_power);
    lv_obj_set_width(ui_Label_charging_power, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_charging_power, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_charging_power, -10);
    lv_obj_set_y(ui_Label_charging_power, -10);
    lv_obj_set_align(ui_Label_charging_power, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_charging_power, "当前充电功率");
    ui_object_set_themeable_style_property(ui_Label_charging_power, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_normal);
    ui_object_set_themeable_style_property(ui_Label_charging_power, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_normal);
    lv_obj_set_style_text_font(ui_Label_charging_power, &ui_font_MiSansRegularFont16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_charging_power_value = lv_label_create(ui_Container_charging_power);
    lv_obj_set_width(ui_Label_charging_power_value, 80);
    lv_obj_set_height(ui_Label_charging_power_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_charging_power_value, -20);
    lv_obj_set_y(ui_Label_charging_power_value, 10);
    lv_obj_set_align(ui_Label_charging_power_value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_charging_power_value, "000 kw");
    ui_object_set_themeable_style_property(ui_Label_charging_power_value, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_normal);
    ui_object_set_themeable_style_property(ui_Label_charging_power_value, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_normal);
    lv_obj_set_style_text_align(ui_Label_charging_power_value, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_charging_power_value, &ui_font_MiSansRegularFont16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_charge = lv_obj_create(ui_Container_center);
    lv_obj_remove_style_all(ui_Container_charge);
    lv_obj_set_width(ui_Container_charge, 198);
    lv_obj_set_height(ui_Container_charge, 64);
    lv_obj_set_x(ui_Container_charge, -204);
    lv_obj_set_y(ui_Container_charge, 148);
    lv_obj_set_align(ui_Container_charge, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container_charge, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Bar_charge = lv_bar_create(ui_Container_charge);
    lv_bar_set_value(ui_Bar_charge, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar_charge, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar_charge, 35);
    lv_obj_set_height(ui_Bar_charge, 19);
    lv_obj_set_x(ui_Bar_charge, -40);
    lv_obj_set_y(ui_Bar_charge, -10);
    lv_obj_set_align(ui_Bar_charge, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Bar_charge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar_charge, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar_charge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Bar_charge, &ui_img_charge_bar_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar_charge, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar_charge, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar_charge, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Bar_charge, &ui_img_charge_bar_on_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label_charge_info = lv_label_create(ui_Container_charge);
    lv_obj_set_width(ui_Label_charge_info, lv_pct(100));
    lv_obj_set_height(ui_Label_charge_info, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_charge_info, 0);
    lv_obj_set_y(ui_Label_charge_info, 15);
    lv_obj_set_align(ui_Label_charge_info, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_charge_info, "预计1h30min后充满");
    ui_object_set_themeable_style_property(ui_Label_charge_info, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_normal);
    ui_object_set_themeable_style_property(ui_Label_charge_info, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_normal);
    lv_obj_set_style_text_align(ui_Label_charge_info, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_charge_info, &ui_font_MiSansRegularFont16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_bottom = lv_obj_create(ui_ScreenMain);
    lv_obj_remove_style_all(ui_Container_bottom);
    lv_obj_set_height(ui_Container_bottom, 55);
    lv_obj_set_width(ui_Container_bottom, lv_pct(100));
    lv_obj_set_align(ui_Container_bottom, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Container_bottom, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_car_status = lv_label_create(ui_Container_bottom);
    lv_obj_set_width(ui_Label_car_status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_car_status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_car_status, -351);
    lv_obj_set_y(ui_Label_car_status, -20);
    lv_obj_set_align(ui_Label_car_status, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label_car_status, "经济");
    lv_obj_set_style_text_color(ui_Label_car_status, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_car_status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_car_status, &ui_font_YouSheBiaoTiFont26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_model_status = lv_label_create(ui_Container_bottom);
    lv_obj_set_width(ui_Label_model_status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_model_status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_model_status, 346);
    lv_obj_set_y(ui_Label_model_status, -20);
    lv_obj_set_align(ui_Label_model_status, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label_model_status, "白天");
    lv_obj_set_style_text_color(ui_Label_model_status, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_model_status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_model_status, &ui_font_YouSheBiaoTiFont26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image_ready = lv_img_create(ui_Container_bottom);
    lv_img_set_src(ui_Image_ready, &ui_img_ready_png);
    lv_obj_set_width(ui_Image_ready, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_ready, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image_ready, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Image_ready, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_ready, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container_tires = lv_obj_create(ui_Container_bottom);
    lv_obj_remove_style_all(ui_Container_tires);
    lv_obj_set_width(ui_Container_tires, 191);
    lv_obj_set_height(ui_Container_tires, lv_pct(100));
    lv_obj_set_x(ui_Container_tires, -185);
    lv_obj_set_y(ui_Container_tires, 0);
    lv_obj_set_align(ui_Container_tires, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Container_tires, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Container_tires, &ui_img_tires_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_tire_pressure_front = lv_label_create(ui_Container_tires);
    lv_obj_set_width(ui_Label_tire_pressure_front, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_tire_pressure_front, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_tire_pressure_front, -56);
    lv_obj_set_y(ui_Label_tire_pressure_front, -15);
    lv_obj_set_align(ui_Label_tire_pressure_front, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_tire_pressure_front, "000");
    lv_obj_set_style_text_color(ui_Label_tire_pressure_front, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_tire_pressure_front, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_tire_pressure_front, &ui_font_MiSansBoldFont16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_tire_temp_front = lv_label_create(ui_Container_tires);
    lv_obj_set_width(ui_Label_tire_temp_front, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_tire_temp_front, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_tire_temp_front, -46);
    lv_obj_set_y(ui_Label_tire_temp_front, 17);
    lv_obj_set_align(ui_Label_tire_temp_front, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_tire_temp_front, "000");
    lv_obj_set_style_text_color(ui_Label_tire_temp_front, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_tire_temp_front, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_tire_temp_front, &ui_font_MiSansBoldFont16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_tire_pressure_rear = lv_label_create(ui_Container_tires);
    lv_obj_set_width(ui_Label_tire_pressure_rear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_tire_pressure_rear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_tire_pressure_rear, 50);
    lv_obj_set_y(ui_Label_tire_pressure_rear, -15);
    lv_obj_set_align(ui_Label_tire_pressure_rear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_tire_pressure_rear, "000");
    lv_obj_set_style_text_color(ui_Label_tire_pressure_rear, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_tire_pressure_rear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_tire_pressure_rear, &ui_font_MiSansBoldFont16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_tire_temp_rear = lv_label_create(ui_Container_tires);
    lv_obj_set_width(ui_Label_tire_temp_rear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_tire_temp_rear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_tire_temp_rear, 60);
    lv_obj_set_y(ui_Label_tire_temp_rear, 16);
    lv_obj_set_align(ui_Label_tire_temp_rear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_tire_temp_rear, "000");
    lv_obj_set_style_text_color(ui_Label_tire_temp_rear, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_tire_temp_rear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_tire_temp_rear, &ui_font_MiSansBoldFont16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container_endurance_mileage = lv_obj_create(ui_Container_bottom);
    lv_obj_remove_style_all(ui_Container_endurance_mileage);
    lv_obj_set_width(ui_Container_endurance_mileage, 208);
    lv_obj_set_height(ui_Container_endurance_mileage, lv_pct(100));
    lv_obj_set_x(ui_Container_endurance_mileage, 175);
    lv_obj_set_y(ui_Container_endurance_mileage, 0);
    lv_obj_set_align(ui_Container_endurance_mileage, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container_endurance_mileage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image_endurance_mileage = lv_img_create(ui_Container_endurance_mileage);
    lv_img_set_src(ui_Image_endurance_mileage, &ui_img_endurance_mileage_png);
    lv_obj_set_width(ui_Image_endurance_mileage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image_endurance_mileage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image_endurance_mileage, -65);
    lv_obj_set_y(ui_Image_endurance_mileage, 0);
    lv_obj_set_align(ui_Image_endurance_mileage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image_endurance_mileage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image_endurance_mileage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label_value_endurance_mileage = lv_label_create(ui_Container_endurance_mileage);
    lv_obj_set_width(ui_Label_value_endurance_mileage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_value_endurance_mileage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_value_endurance_mileage, 20);
    lv_obj_set_y(ui_Label_value_endurance_mileage, -10);
    lv_obj_set_align(ui_Label_value_endurance_mileage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_value_endurance_mileage, "302 km");
    lv_obj_set_style_text_color(ui_Label_value_endurance_mileage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_value_endurance_mileage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_value_endurance_mileage, &ui_font_MiSansBoldFont24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar_endurance_mileage = lv_bar_create(ui_Container_endurance_mileage);
    lv_bar_set_value(ui_Bar_endurance_mileage, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar_endurance_mileage, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar_endurance_mileage, 130);
    lv_obj_set_height(ui_Bar_endurance_mileage, 12);
    lv_obj_set_x(ui_Bar_endurance_mileage, 25);
    lv_obj_set_y(ui_Bar_endurance_mileage, 12);
    lv_obj_set_align(ui_Bar_endurance_mileage, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar_endurance_mileage, lv_color_hex(0x838383), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar_endurance_mileage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar_endurance_mileage, lv_color_hex(0x00FF1E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar_endurance_mileage, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Button_test = lv_btn_create(ui_ScreenMain);
    lv_obj_set_width(ui_Button_test, 100);
    lv_obj_set_height(ui_Button_test, 50);
    lv_obj_set_x(ui_Button_test, 213);
    lv_obj_set_y(ui_Button_test, 145);
    lv_obj_set_align(ui_Button_test, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button_test, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button_test, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button_test, ui_event_Button_test, LV_EVENT_ALL, NULL);

}

void ui_ScreenMain_screen_destroy(void)
{
    if(ui_ScreenMain) lv_obj_del(ui_ScreenMain);

    // NULL screen variables
    ui_ScreenMain = NULL;
    ui_Bar_speed_bg = NULL;
    ui_Bar_charge_bg = NULL;
    ui_Bar_power_bg = NULL;
    ui_Image_bg1 = NULL;
    ui_Image_bg2 = NULL;
    ui_Container_top = NULL;
    ui_Container_time = NULL;
    ui_Label_time = NULL;
    ui_Label_time_marker = NULL;
    ui_Container_connect = NULL;
    ui_Image_bluetooth_status = NULL;
    ui_Image_wifi_status = NULL;
    ui_Image_low_beam = NULL;
    ui_Image_high_beam = NULL;
    ui_Image_clearance_lamp = NULL;
    ui_Image_day_time = NULL;
    ui_Image_location = NULL;
    ui_Image_ccs = NULL;
    ui_Image_motor_fault = NULL;
    ui_Image_soc_temp_high = NULL;
    ui_Container_center = NULL;
    ui_Image_left = NULL;
    ui_Image_right = NULL;
    ui_Label_speed_value = NULL;
    ui_Label_gear_value = NULL;
    ui_Label_charge_value = NULL;
    ui_Panel_warning = NULL;
    ui_Image_warning = NULL;
    ui_Label_warning_info = NULL;
    ui_Container_odo = NULL;
    ui_Label_odo = NULL;
    ui_Label_odo_value = NULL;
    ui_Label_odo_km = NULL;
    ui_Container_trip = NULL;
    ui_Label_trip = NULL;
    ui_Label_trip_value = NULL;
    ui_Label_trip_km = NULL;
    ui_Container_info_left = NULL;
    ui_Container_reverse_image = NULL;
    ui_Button_reverse_image = NULL;
    ui_Image_reverse_image = NULL;
    ui_Label_reverse_image = NULL;
    ui_Container_projection_screen = NULL;
    ui_Button_projection_screen = NULL;
    ui_Image_projection_screen = NULL;
    ui_Label_projection_screen = NULL;
    ui_Container_bluetooth = NULL;
    ui_Button_bluetooth = NULL;
    ui_Image_bluetooth = NULL;
    ui_Label_bluetooth = NULL;
    ui_Container_music = NULL;
    ui_Button_music = NULL;
    ui_Image_music = NULL;
    ui_Label_music = NULL;
    ui_Container_info_right = NULL;
    ui_Container_current_drain = NULL;
    ui_Label_current_drain = NULL;
    ui_Label_current_drain_value = NULL;
    ui_Container_instantaneous_power = NULL;
    ui_Label_instantaneous_power = NULL;
    ui_Label_instantaneous_power_value = NULL;
    ui_Container_surplus_power = NULL;
    ui_Label_surplus_power = NULL;
    ui_Label_surplus_power_value = NULL;
    ui_Container_charging_power = NULL;
    ui_Label_charging_power = NULL;
    ui_Label_charging_power_value = NULL;
    ui_Container_charge = NULL;
    ui_Bar_charge = NULL;
    ui_Label_charge_info = NULL;
    ui_Container_bottom = NULL;
    ui_Label_car_status = NULL;
    ui_Label_model_status = NULL;
    ui_Image_ready = NULL;
    ui_Container_tires = NULL;
    ui_Label_tire_pressure_front = NULL;
    ui_Label_tire_temp_front = NULL;
    ui_Label_tire_pressure_rear = NULL;
    ui_Label_tire_temp_rear = NULL;
    ui_Container_endurance_mileage = NULL;
    ui_Image_endurance_mileage = NULL;
    ui_Label_value_endurance_mileage = NULL;
    ui_Bar_endurance_mileage = NULL;
    ui_Button_test = NULL;

}
