// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENMAIN_H
#define UI_SCREENMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenMain
extern void ui_ScreenMain_screen_init(void);
extern void ui_ScreenMain_screen_destroy(void);
extern lv_obj_t * ui_ScreenMain;
extern lv_obj_t * ui_Bar_speed_bg;
extern lv_obj_t * ui_Bar_charge_bg;
extern lv_obj_t * ui_Bar_power_bg;
extern lv_obj_t * ui_Image_bg1;
extern lv_obj_t * ui_Image_bg2;
extern lv_obj_t * ui_Container_top;
extern lv_obj_t * ui_Container_time;
extern lv_obj_t * ui_Label_time;
extern lv_obj_t * ui_Label_time_marker;
extern lv_obj_t * ui_Container_connect;
extern lv_obj_t * ui_Image_bluetooth_status;
extern lv_obj_t * ui_Image_wifi_status;
extern lv_obj_t * ui_Image_low_beam;
extern lv_obj_t * ui_Image_high_beam;
extern lv_obj_t * ui_Image_clearance_lamp;
extern lv_obj_t * ui_Image_day_time;
extern lv_obj_t * ui_Image_location;
extern lv_obj_t * ui_Image_ccs;
extern lv_obj_t * ui_Image_motor_fault;
extern lv_obj_t * ui_Image_soc_temp_high;
extern lv_obj_t * ui_Container_center;
extern lv_obj_t * ui_Image_left;
extern lv_obj_t * ui_Image_right;
extern lv_obj_t * ui_Label_speed_value;
extern lv_obj_t * ui_Label_gear_value;
extern lv_obj_t * ui_Label_charge_value;
extern lv_obj_t * ui_Panel_warning;
extern lv_obj_t * ui_Image_warning;
extern lv_obj_t * ui_Label_warning_info;
extern lv_obj_t * ui_Container_odo;
extern lv_obj_t * ui_Label_odo;
extern lv_obj_t * ui_Label_odo_value;
extern lv_obj_t * ui_Label_odo_km;
extern lv_obj_t * ui_Container_trip;
extern lv_obj_t * ui_Label_trip;
extern lv_obj_t * ui_Label_trip_value;
extern lv_obj_t * ui_Label_trip_km;
extern lv_obj_t * ui_Container_info_left;
extern lv_obj_t * ui_Container_reverse_image;
extern lv_obj_t * ui_Button_reverse_image;
extern lv_obj_t * ui_Image_reverse_image;
extern lv_obj_t * ui_Label_reverse_image;
extern lv_obj_t * ui_Container_projection_screen;
extern lv_obj_t * ui_Button_projection_screen;
extern lv_obj_t * ui_Image_projection_screen;
extern lv_obj_t * ui_Label_projection_screen;
extern lv_obj_t * ui_Container_bluetooth;
extern lv_obj_t * ui_Button_bluetooth;
extern lv_obj_t * ui_Image_bluetooth;
extern lv_obj_t * ui_Label_bluetooth;
extern lv_obj_t * ui_Container_music;
extern lv_obj_t * ui_Button_music;
extern lv_obj_t * ui_Image_music;
extern lv_obj_t * ui_Label_music;
extern lv_obj_t * ui_Container_info_right;
extern lv_obj_t * ui_Container_current_drain;
extern lv_obj_t * ui_Label_current_drain;
extern lv_obj_t * ui_Label_current_drain_value;
extern lv_obj_t * ui_Container_instantaneous_power;
extern lv_obj_t * ui_Label_instantaneous_power;
extern lv_obj_t * ui_Label_instantaneous_power_value;
extern lv_obj_t * ui_Container_surplus_power;
extern lv_obj_t * ui_Label_surplus_power;
extern lv_obj_t * ui_Label_surplus_power_value;
extern lv_obj_t * ui_Container_charging_power;
extern lv_obj_t * ui_Label_charging_power;
extern lv_obj_t * ui_Label_charging_power_value;
extern lv_obj_t * ui_Container_charge;
extern lv_obj_t * ui_Bar_charge;
extern lv_obj_t * ui_Label_charge_info;
extern lv_obj_t * ui_Container_bottom;
extern lv_obj_t * ui_Label_car_status;
extern lv_obj_t * ui_Label_model_status;
extern lv_obj_t * ui_Image_ready;
extern lv_obj_t * ui_Container_tires;
extern lv_obj_t * ui_Label_tire_pressure_front;
extern lv_obj_t * ui_Label_tire_temp_front;
extern lv_obj_t * ui_Label_tire_pressure_rear;
extern lv_obj_t * ui_Label_tire_temp_rear;
extern lv_obj_t * ui_Container_endurance_mileage;
extern lv_obj_t * ui_Image_endurance_mileage;
extern lv_obj_t * ui_Label_value_endurance_mileage;
extern lv_obj_t * ui_Bar_endurance_mileage;
extern void ui_event_Button_test(lv_event_t * e);
extern lv_obj_t * ui_Button_test;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

